INSERT INTO FAMILY (MEMBERID,FIRSTNAME,LASTNAME,AGE,DEPARTMENT,RESIDENCE)
VALUES
(1,'EMMANUEL','NYINAKU',53,'BUILDING_TECH','DABOASE'),
(2,'VICTORIA','KOOMSON',49,'TRADE','DABOASE'),
(3,'FELIX','NYINAKU',32,'PLANNING','KOTEI'),
(4,'AUGUSTINA','NYINAKU',28,'COMP_SCIENCE','TAKORADI'),
(5,'FRANCISCA','NYINAKU',25,'RURAL_DEV','DABOASE'),
(6,'NANA','OFORI',22,'GEOMATIC','AYEDUASE'),
(7,'NANA','KWAME',16,'GEN_ARTS','ACCRA');
