INSERT INTO EMPLOYEES (EMPLOYEEID,FIRSTNAME,LASTNAME,AGE,DEPARTMENT)
VALUES
(1,'NANA','OFORI',22,'GEOMATIC'),
(2,'KWAME','ADDO',22,'ELECTRICAL'),
(3,'FELIX','NYINAKU',22,'PLANNING'),
(4,'AUGUSTINA','ADDO',22,'COMPUTER'),
(5,'FRANCISCA','ADDO',22,'SOCIOSO');